### PR TITLE
add transform optional parameter to function plot_pole_dp_dm

### PR DESCRIPTION
**Pull request by duserzym**
I hope to make this change to address issue #692

### CODE REVIEW

**Comment by Swanson-Hysell** [comment]
Should we make the default ccrs.geodetic() or will that cause other issues?

**Comment by duserzym** [comment]
My experience is that PlateCarree usually works fine and geodetic has other issues such as making weird filled polygons instead of a circle/ellipse, and I felt that geodetic more often has issues for our applications.

**Comment by Swanson-Hysell** [comment]
That makes sense. Perhaps we can add to the documentation of the parameter that it will rarely need to be changed?

**Comment by Swanson-Hysell** [comment]
This should do the trick!

**Pull request merged**
