### PR TITLE
fix matrix quoted values and cv validation

### PR DESCRIPTION
**Pull request by rminnett**
Here is a proposed fix for validate_upload3 along with a notebook for testing the fix. It requires the "regex" (and not just the "re") package for the zero-length look-ahead regular expressions to match the quoted strings properly. 

validate_upload2 might also need a similar fix and a unit test with data files that include valid and invalid examples of List, Dictionary, and Matrix values would be good.

### CODE REVIEW

**Comment by rminnett** [comment]
The Travis CI builds are failing without the regex package.

**Comment by moonshoes87** [comment]
@rminnett, thanks for this.  I haven't used the `re` module extensively, but could you explain what `regex` provides that is missing in `re`?  I'm not sure I understand.

**Comment by rminnett** [comment]
@moonshoes87, the `re` module doesn't implement zero-width matches properly, which are necessary for the look ahead quote matches in this case. https://pypi.org/project/regex/ seems to suggest that in python 3.7+ it does a better job, but when I was testing with 3.8.1 it worked with `regex` and not `re`. Maybe the regular expression I'm using for splitting is an edge case that is still not handled correctly in `re`.

**Comment by rminnett** [comment]
@moonshoes87 In case the regular expression itself is too cryptic, here's an explanation of the matching looking for pairs of quotes in the rest of the string, indicating that the splitting character is outside of a quoted string:
```
;           // Split on semicolon
(?=         // Followed by (zero-width matching)
   (?:      // Start a non-capture group so the result of splitting will be correct
     [^"]*  // 0 or more non-quote characters
     "      // 1 quote
     [^"]*  // 0 or more non-quote characters
     "      // 1 quote
   )*       // 0 or more repetition of non-capture group (multiple of 2 quotes will be even)
   [^"]*    // Finally 0 or more non-quotes
   $        // Till the end  (This is necessary, else every comma will satisfy the condition)
)
```

**Comment by moonshoes87** [comment]
Thanks for walking me through this, Rupert.  Could you give me an example of where this is failing with `re`?  I wasn't able to find an edge case where `re` and `regex` didn't produce the same results.

I was hoping to avoid adding a new dependency if possible, since installing everything is already a challenge for many users.  The Anaconda distribution comes bundled with `re` but not `regex`.  Let me know what you think.

**Comment by rminnett** [comment]
You're right! I just checked on Python 3.7.6 and 3.8.1 and they both work with the `re` module. Perhaps I was testing with an old kernel attached to the notebook at the time! I pushed another commit without the `regex` import.

As I was thinking about it, it might also be good to report an error if there's an odd number of double quotes in the `cell_values` string because the `re.split()` won't handle it correctly and it's probably a mistake.

**Pull request merged**
