### PR TITLE
add zorder optional parameter to plot_di and plot_di_mean

### PR DESCRIPTION
**Pull request by duserzym**

### CODE REVIEW

**Comment by Swanson-Hysell** [comment]
Adding this as an optional parameter is a good idea. However, does it make sense to set the default to be 1? What typically happens when a zorder is not set in matplotlib? Do we want to be overriding that with 1?

**Comment by Swanson-Hysell** [comment]
I guess that doing the same as line (zorder = 2) might make the most sense?

**Comment by duserzym** [comment]
I just made the changes for the default zorder values.

**Comment by duserzym** [comment]
I keep running into this zorder issue when doing stereonet plots. I am merging this branch to main.

**Comment by Swanson-Hysell** [comment]
Good deal!

**Pull request merged**
